// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tu_Jardin_App.Server.Data;

namespace Tu_Jardin_App.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210825163238_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Tu_Jardin_App.Shared.Models.Achieve", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Agricultor")
                        .HasColumnType("bit");

                    b.Property<bool>("Cosecha")
                        .HasColumnType("bit");

                    b.Property<bool>("Guardabosques")
                        .HasColumnType("bit");

                    b.Property<bool>("Hermitano")
                        .HasColumnType("bit");

                    b.Property<bool>("Jardin")
                        .HasColumnType("bit");

                    b.Property<bool>("Jardinero")
                        .HasColumnType("bit");

                    b.Property<bool>("Lluvia")
                        .HasColumnType("bit");

                    b.Property<bool>("Riego")
                        .HasColumnType("bit");

                    b.Property<bool>("Semillero")
                        .HasColumnType("bit");

                    b.Property<bool>("Vida")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Achieves");
                });

            modelBuilder.Entity("Tu_Jardin_App.Shared.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AchievementsId")
                        .HasColumnType("int");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Seeddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AchievementsId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("Tu_Jardin_App.Shared.Models.Plant", b =>
                {
                    b.HasOne("Tu_Jardin_App.Shared.Models.Achieve", "Achievements")
                        .WithMany()
                        .HasForeignKey("AchievementsId");

                    b.Navigation("Achievements");
                });
#pragma warning restore 612, 618
        }
    }
}
